// <auto-generated />
using System;
using HomeWorkOfProductAndCategory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWorkOfProductAndCategory.Migrations
{
    [DbContext(typeof(ProductDbContextcs))]
    partial class ProductDbContextcsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeWorkOfProductAndCategory.Models.Categorycs", b =>
                {
                    b.Property<int>("Catid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Catid"));

                    b.Property<string>("CatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Catid");

                    b.ToTable("Categorycs");
                });

            modelBuilder.Entity("HomeWorkOfProductAndCategory.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("Categoryid")
                        .HasColumnType("int");

                    b.Property<string>("ProName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("Categoryid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("HomeWorkOfProductAndCategory.Models.Product", b =>
                {
                    b.HasOne("HomeWorkOfProductAndCategory.Models.Categorycs", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeWorkOfProductAndCategory.Models.Categorycs", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
